In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from ast import literal_eval
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import wordnet


import warnings; warnings.simplefilter('ignore')

In [2]:
movies = pd.read_csv('/content/drive/MyDrive/LLM RAG Recommender - MovieLens/Data/ml-32m/movies_enriched.csv')

In [3]:
movies.head()

,movieId,tmdbId,title,overview,tagline,runtime,budget,revenue,release_date,genres,vote_average,vote_count,poster_path,director,cast,keywords,production_companies,collection_name,tmdb_recommendation_ids
0,1,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",The adventure takes off when toys come to life!,81,30000000,394436586,1995-11-22,"['Family', 'Comedy', 'Animation', 'Adventure']",7.970,19297,/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg,John Lasseter,"['Tom Hanks', 'Tim Allen', 'Don Rickles', 'Jim...","['rescue', 'friendship', 'mission', 'jealousy'...",['Pixar'],Toy Story Collection,"[863, 9487, 10193, 8587, 585]"
1,2,8844,Jumanji,When siblings Judy and Peter discover an encha...,It's a jungle in here.,104,65000000,262821940,1995-12-15,"['Adventure', 'Fantasy', 'Family']",7.242,10971,/iWV47r6kFneCiApgrMII5HSkfHw.jpg,Joe Johnston,"['Robin Williams', 'Kirsten Dunst', 'Bradley P...","['giant insect', 'board game', 'disappearance'...","['TriStar Pictures', 'Interscope Communication...",Jumanji Collection,"[353486, 6795, 788, 1593, 879]"
2,3,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,101,25000000,71500000,1995-12-22,"['Romance', 'Comedy']",6.500,409,/1FSXpj5e8l4KH6nVFO5SPUeraOt.jpg,Howard Deutch,"['Walter Matthau', 'Jack Lemmon', 'Ann-Margret...","['fishing', 'sequel', 'old man', 'best friend'...","['Lancaster Gate', 'Warner Bros. Pictures']",Grumpy Old Men Collection,"[11520, 39242, 24732, 30066, 50766]"
3,4,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,127,16000000,81452156,1995-12-22,"['Comedy', 'Drama', 'Romance']",6.260,179,/qJU6rfil5xLVb5HpJsmmfeSK254.jpg,Forest Whitaker,"['Whitney Houston', 'Angela Bassett', 'Loretta...","['based on novel or book', 'single mother', 'd...",['20th Century Fox'],NaN,"[31000, 21539, 16158, 33644, 64255]"
4,5,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,Just when his world is back to normal... he's ...,106,0,76594107,1995-12-08,"['Comedy', 'Family']",6.266,777,/rj4LBtwQ0uGrpBnCELr716Qo3mw.jpg,Charles Shyer,"['Steve Martin', 'Diane Keaton', 'Martin Short...","['daughter', 'baby', 'parent child relationshi...","['Touchstone Pictures', 'Sandollar Productions']",Father of the Bride (Steve Martin) Collection,"[11846, 65137, 22968, 14949, 13759]"

In [4]:
movies.shape

(86315, 19)

In [5]:
import numpy as np
from ast import literal_eval

# replacing nan with empty list []
movies['genres'] = movies['genres'].apply(lambda x: [] if x is np.nan else x)

# converting string into actual list which is the python object
movies['genres'] = movies['genres'].apply(lambda x: literal_eval(x) if isinstance(x, str) else x)

# Might remove later
movies['genres'] = movies['genres'].apply(lambda x: [i for i in x] if isinstance(x, list) else [])

In [6]:
movies['genres']

0        [Family, Comedy, Animation, Adventure]
1                  [Adventure, Fantasy, Family]
2                             [Romance, Comedy]
3                      [Comedy, Drama, Romance]
4                              [Comedy, Family]
                          ...
86310                                   [Drama]
86311                           [Drama, Comedy]
86312                                   [Drama]
86313                                   [Drama]
86314          [Documentary, Action, Adventure]
Name: genres, Length: 86315, dtype: object

In [7]:
movies.head(2)

,movieId,tmdbId,title,overview,tagline,runtime,budget,revenue,release_date,genres,vote_average,vote_count,poster_path,director,cast,keywords,production_companies,collection_name,tmdb_recommendation_ids
0,1,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",The adventure takes off when toys come to life!,81,30000000,394436586,1995-11-22,"[Family, Comedy, Animation, Adventure]",7.970,19297,/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg,John Lasseter,"['Tom Hanks', 'Tim Allen', 'Don Rickles', 'Jim...","['rescue', 'friendship', 'mission', 'jealousy'...",['Pixar'],Toy Story Collection,"[863, 9487, 10193, 8587, 585]"
1,2,8844,Jumanji,When siblings Judy and Peter discover an encha...,It's a jungle in here.,104,65000000,262821940,1995-12-15,"[Adventure, Fantasy, Family]",7.242,10971,/iWV47r6kFneCiApgrMII5HSkfHw.jpg,Joe Johnston,"['Robin Williams', 'Kirsten Dunst', 'Bradley P...","['giant insect', 'board game', 'disappearance'...","['TriStar Pictures', 'Interscope Communication...",Jumanji Collection,"[353486, 6795, 788, 1593, 879]"

In [8]:
movies['overview'] = movies['overview'].fillna('')
movies['tagline'] = movies['tagline'].fillna('')
movies['description'] = movies['overview'] + movies['tagline']
movies['title'] = movies['title'].fillna('')
movies['director'] = movies['director'].fillna('')


movies['keywords'] = movies['keywords'].apply(lambda x: [] if x is np.nan else x)
movies['keywords'] = movies['keywords'].apply(lambda x: literal_eval(x) if isinstance(x, str) else x)
movies['keywords'] = movies['keywords'].apply(lambda x: [i for i in x] if isinstance(x, list) else [])

movies['cast'] = movies['cast'].apply(lambda x: [] if x is np.nan else x)
movies['cast'] = movies['cast'].apply(lambda x: literal_eval(x) if isinstance(x, str) else x)
movies['cast'] = movies['cast'].apply(lambda x: [i for i in x] if isinstance(x, list) else [])
movies['cast'] = movies['cast'].apply(lambda x: x[:3] if len(x) >=3 else x)

movies['production_companies'] = movies['production_companies'].apply(lambda x: [] if x is np.nan else x)
movies['production_companies'] = movies['production_companies'].apply(lambda x: literal_eval(x) if isinstance(x, str) else x)
movies['production_companies'] = movies['production_companies'].apply(lambda x: [i for i in x] if isinstance(x, list) else [])
movies['production_companies'] = movies['production_companies'].apply(lambda x: x[:3] if len(x) >=3 else x)

In [9]:
movies.cast, movies.production_companies

(0                      [Tom Hanks, Tim Allen, Don Rickles]
 1          [Robin Williams, Kirsten Dunst, Bradley Pierce]
 2               [Walter Matthau, Jack Lemmon, Ann-Margret]
 3        [Whitney Houston, Angela Bassett, Loretta Devine]
 4               [Steve Martin, Diane Keaton, Martin Short]
                                ...
 86310          [Damián Alcázar, Grapa Paola, María Zubiri]
 86311    [Siobhan Fallon Hogan, Peter Macon, Robert Pat...
 86312    [Taraneh Alidoosti, Mahtab Keramati, Masoud Ka...
 86313      [Jan Sterling, James MacArthur, William Windom]
 86314                            [Ueli Steck, Dani Arnold]
 Name: cast, Length: 86315, dtype: object,
 0                                                  [Pixar]
 1        [TriStar Pictures, Interscope Communications, ...
 2                  [Lancaster Gate, Warner Bros. Pictures]
 3                                       [20th Century Fox]
 4             [Touchstone Pictures, Sandollar Productions]
                                ...
 86310               [Chullachaki Producciones, Gema Films]
 86311    [Emerald Caz Productions, Legendary Goat Produ...
 86312                [Andisheh Pardis Jam, Katara Studios]
 86313                  [Commonwealth United Entertainment]
 86314                                [Pitch International]
 Name: production_companies, Length: 86315, dtype: object)

In [10]:
movies.description

0        Led by Woody, Andy's toys live happily in his ...
1        When siblings Judy and Peter discover an encha...
2        A family wedding reignites the ancient feud be...
3        Cheated on, mistreated and stepped on, the wom...
4        Just when George Banks has recovered from his ...
                               ...
86310    Ronnie Monroy has had an unmeaningful life as ...
86311    A death row prisoner with 10 days left to live...
86312    Elham is a young, divorced Iranian woman. Seek...
86313    In Vietnam, aspiring actor Johnny Taylor is gi...
86314    Fearless alpine climbers Ueli Steck and Dani A...
Name: description, Length: 86315, dtype: object

In [11]:
movies['cast'] = movies['cast'].apply(lambda x: [str.lower(i.replace(" ", "")) for i in x])
movies['director'] = movies['director'].apply(lambda x: str.lower(x.replace(" ", "")))

In [12]:
def weighted_rating(x, m, C):
    v = x['vote_count']
    R = x['vote_average']
    return (v/(v+m) * R) + (m/(m+v) * C)

In [14]:
tfidf = TfidfVectorizer(stop_words='english', ngram_range=(1, 2), min_df=1)

In [15]:
tfidf_matrix = tfidf.fit_transform(movies['description'])

In [16]:
tfidf_matrix.shape

(86315, 1736558)

In [17]:
from ast import literal_eval
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
def create_soup(x):
    return (
        ' '.join(x['keywords']) + ' ' +
        ' '.join(x['cast']) + ' ' +
        x['director'] + ' ' +
        ' '.join(x['genres']) + ' ' +
        ' '.join(x['production_companies'])
    )

movies['soup'] = movies.apply(create_soup, axis=1)

In [20]:
count = CountVectorizer(analyzer='word', ngram_range=(1, 1), min_df=1, stop_words='english')
count_matrix = count.fit_transform(movies['soup'])

In [21]:
count_matrix

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 1332414 stored elements and shape (86315, 162458)>

In [22]:
from scipy.sparse import hstack

# Stack the two matrices horizontally
combined_matrix = hstack([tfidf_matrix, count_matrix])

In [23]:
combined_matrix.shape

(86315, 1899016)

In [25]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np


movies = movies.reset_index()
indices = pd.Series(movies.index, index=movies['title'])

In [44]:
def get_recommendations_batch(titles, combined_matrix, movies_df, indices, batch_size=10, top_n=10, candidate_pool=50):

    results = {}

    # Process in batches
    for i in range(0, len(titles), batch_size):
        batch_titles = titles[i : i + batch_size]

        # Get valid indices
        batch_indices = []
        valid_titles = []

        for t in batch_titles:
            if t in indices:
                idx = indices[t]
                # Handle duplicate titles
                if isinstance(idx, (pd.Series, pd.Index, np.ndarray, list)):
                    idx = idx.iloc[0] if hasattr(idx, 'iloc') else idx[0]

                batch_indices.append(idx)
                valid_titles.append(t)
            else:
                print(f"Warning: '{t}' not found in indices.")

        if not batch_indices:
            continue

        # Extract feature vectors
        target_vectors = combined_matrix[batch_indices]

        # Compute cosine similarity
        batch_sim_scores = cosine_similarity(target_vectors, combined_matrix)

        # Process each movie
        for k, title in enumerate(valid_titles):
            scores = batch_sim_scores[k]

            top_indices = np.argpartition(scores, -(candidate_pool + 1))[-(candidate_pool + 1):]
            top_indices = top_indices[np.argsort(scores[top_indices])[::-1]]

            # Exclude input movie
            final_indices = [idx for idx in top_indices if idx != batch_indices[k]][:candidate_pool]

            # Get metadata
            recs = movies_df.iloc[final_indices][['title', 'vote_count', 'vote_average', 'year']].copy()
            recs['similarity'] = scores[final_indices]

            # Filter for Quality

            C = recs['vote_average'].mean()
            m = recs['vote_count'].quantile(0.20)
            recs = recs[recs['vote_count'] >= m]

            # Calculate Score
            recs['wr_score'] = recs.apply(lambda x: weighted_rating(x, m, C), axis=1)


            results[title] = recs.sort_values('similarity', ascending=False).head(top_n)

    return results

In [46]:
import time


test_movies = [
    'Toy Story', 'Jumanji', 'Grumpier Old Men', 'Heat', 'Sabrina', 'Tom and Huck',
    'Sudden Death', 'GoldenEye', 'The American President', 'Dracula: Dead and Loving It'
]

start = time.time()
recs_1 = get_recommendations_batch(test_movies, combined_matrix, movies, indices, batch_size=1)
end = time.time()
print(f"Batch Size 1 took: {end - start:.4f} seconds")


recs_10 = get_recommendations_batch(test_movies, combined_matrix, movies, indices, batch_size=1000)



print(recs_10['Jumanji'])

Batch Size 1 took: 5.5198 seconds
                                                   title  vote_count  \
19908                     Percy Jackson: Sea of Monsters        5264
14268  Percy Jackson & the Olympians: The Lightning T...        7669
12291           The Chronicles of Narnia: Prince Caspian        6598
14310                                Alice in Wonderland       14465
15199                                Alice in Wonderland          62
2057                               The NeverEnding Story        4219
19254                          Oz the Great and Powerful        6675
32323                                   Ready Player One       16372
49525                     Jumanji: Welcome to the Jungle       14138
57781                                      Chaos Walking        2459

       vote_average  year  similarity  wr_score
19908         6.025  2013    0.344829  6.027948
14268         6.209  2010    0.330672  6.209574
12291         6.628  2008    0.329362  6.624816
14310         6.637  2010    0.327019  6.635502
15199         6.081  1933    0.326857  6.180599
2057          7.205  1984    0.325905  7.191795
19254         5.900  2013    0.322967  5.903466
32323         7.584  2018    0.314841  7.579149
49525         6.819  2017    0.314017  6.816683
57781         6.563  2021    0.311086  6.556164

In [49]:
import time
import random

# Selecting 100 Random Movies
random_titles = movies['title'].sample(n=100, random_state=42).tolist()

print(f"Selected {len(random_titles)} random movies for testing.")
print(f"Examples: {random_titles[:5]}")




test_results = get_recommendations_batch(
    random_titles,
    combined_matrix,
    movies,
    indices,
    batch_size=1000,
    top_n=50,
    candidate_pool=100
)


# looking at random results to see if they make sense
for i in range(10):
    title = random_titles[i]
    print(f"\nSource Movie: {title}")
    if title in test_results:
        print(test_results[title][['title', 'similarity', 'wr_score']].head(100))
    else:
        print("No recommendations generated (possibly filtered out).")

Selected 100 random movies for testing.
Examples: ['The Penthouse', 'Jinn', 'Robot on the Road', 'Pigs 2: The Last Blood', 'Crooklyn']

Source Movie: The Penthouse
                            title  similarity  wr_score
52300            The Lost Brother    0.410391  6.778114
51611             Dead Slow Ahead    0.389490  6.482203
51579                 Mrs. Harris    0.382692  5.704024
79083            The Night Doctor    0.381771  6.445280
23937             Penthouse North    0.377815  5.710899
48371               The Next Skin    0.374634  5.696419
23614                  On the Ice    0.374634  6.108066
23992        The Body of My Enemy    0.368606  6.324577
39647         A Friend of Vincent    0.368563  5.787305
24059                       Prowl    0.368421  5.030127
83654                    Scorpion    0.368421  5.446472
67927                  Dirt Music    0.368421  6.138481
68112        The Crimes That Bind    0.367884  6.397501
15068              8th Wonderland    0.367884  6.051813
10263               Separate Lies    0.367884  5.748818
34350                     24 Days    0.367884  6.480244
36368                       Wazir    0.367065  6.602487
6610                   Demonlover    0.359937  5.789139
58253                  Viper Club    0.359862  5.512870
37988                        Amar    0.359303  4.670466
9915                  Vodka Lemon    0.359092  6.392259
20937        Cold Comes the Night    0.359092  5.411229
33335               An Open Heart    0.359092  5.458489
51475  Emmanuelle: Queen of Sados    0.359092  6.169835
18440             California Solo    0.359092  5.691786
37666        The Tree of Guernica    0.359092  5.939066
23112               So Much Water    0.359092  5.479956
62028              American Woman    0.359092  5.193382
75514              White on White    0.359092  5.900575
22395                  Copenhagen    0.359092  6.517831
45170                      Django    0.359092  6.255902
39646              The North Star    0.355966  6.031527
42821                Interruption    0.355516  6.358203
23196              Orders to Kill    0.355409  6.674021
55850               Close Enemies    0.355409  5.902408
9275            The Galíndez File    0.355409  4.756988
71351                   The Flood    0.353209  5.037305
8069                         Novo    0.351011  5.441938
35363            Adieu Philippine    0.350534  6.675345
20384         The Wonderful Crook    0.350438  5.554835
47351                        Moka    0.350438  6.004330
51827               Thirst Street    0.350438  4.780590
76601                  The Tunnel    0.350438  4.507133
85528      The Path of Excellence    0.350438  6.073274
60652                 French Tour    0.350438  5.382414
10173          L.A. Without a Map    0.350438  5.756917
61234                      Jaulas    0.345857  5.689258
79072     The Last Thing Mary Saw    0.344292  6.019387
60422                  L'Addition    0.344240  5.058203
61467                 22nd Of May    0.344124  6.007357

Source Movie: Jinn
                            title  similarity  wr_score
62708             My Soul to Keep    0.474342  5.345383
56034                Warning Shot    0.324443  5.333128
82374                      Sardar    0.294174  6.381013
61260                Winter Ridge    0.284096  5.240681
41302                        H8RZ    0.283473  5.348985
14640          The Forbidden Door    0.283473  6.282771
14184                 Defenseless    0.282843  5.133261
5152                  High Crimes    0.276079  6.341478
1026            Shadow Conspiracy    0.274013  5.076461
81510                    Stowaway    0.273861  6.062750
62337                    Deserted    0.273861  4.890627
19019           Blood of My Blood    0.273861  6.389985
39901    To the Ends of the Earth    0.273861  5.639985
61927               The Corrupted    0.273861  5.968587
35416                      Talvar    0.272166  7.327836
58691              Order of Chaos    0.267444  4.894557
46804                   Mudhalvan    0.267261  6.499277
7002                The Statement    0.265751  5.596339
23462        The Aggression Scale    0.265615  5.596299
66621                      Awoken    0.265540  5.681617
70383  May the Devil Take You Too    0.265165  6.619494
77620                   Dangerous    0.265165  5.987905
62932                       Spell    0.265165  5.214448
5234                   Unfaithful    0.258199  6.663711
30426                 Wild Horses    0.257696  4.931199
79320                  Glasshouse    0.257480  5.810965
40459               Guns for Hire    0.257395  4.980858
74623              I Am All Girls    0.257248  6.511563
59201                   Billy Boy    0.257248  5.048908
5672          The Weight of Water    0.257248  5.461962
56172                   Bel Canto    0.257248  5.420262
76899                      Plan A    0.257248  6.050246
6298             Cloak and Dagger    0.257248  6.313803
31962                The Invoking    0.257248  4.486594
82135           Dead for a Dollar    0.257248  5.821345
4573                 Original Sin    0.254000  6.090011
24641                   Malicious    0.250452  4.997583
55718                     Replace    0.250417  5.078993
67458          TRON: The Next Day    0.250241  5.681280
45325                       Bokeh    0.250176  5.423137
11081                     Sirocco    0.250000  5.807788
62793                  Jallikattu    0.250000  6.576092
56401                Bayou Caviar    0.250000  4.947891
61928                 Hellmington    0.250000  5.230271
63396            American Dreamer    0.250000  5.917488
6589                  See No Evil    0.250000  6.438323
15468                           M    0.250000  6.142822
8144         Whispers in the Dark    0.250000  5.052711
33776                   Big Match    0.250000  6.547491
1739          The Gingerbread Man    0.250000  5.574546

Source Movie: Robot on the Road
                                                   title  similarity  wr_score
61164                               Technological Threat    0.418121  5.888479
69513                           Live Freaky! Die Freaky!    0.358057  4.868091
46285                   Tamala 2010: A Punk Cat in Space    0.350823  6.230420
27133                                  Stitch! The Movie    0.346688  6.414412
49805                       The Centrifuge Brain Project    0.339683  6.749524
58939                                              Puppy    0.336646  7.154364
58938                              Panic in the Mailroom    0.336336  6.756564
22429                   LEGO Hero Factory: Savage Planet    0.336336  6.201412
71102               Jimmy Neutron: Win, Lose and Kaboom!    0.336336  6.632486
68199  Phineas and Ferb the Movie: Candace Against th...    0.336336  7.233364
77061                                            Tempbot    0.336323  6.236092
38462                                            Hot Bot    0.335142  4.367130
56121                                            Big Ear    0.334497  6.525604
19256                       Tripping the Rift: The Movie    0.334497  5.421723
69756                            Trump vs the Illuminati    0.334497  3.785814
66606                                           Marooned    0.328335  6.451857
66213                 Giant God Warrior Appears in Tokyo    0.326357  6.506834
11483  Aqua Teen Hunger Force Colon Movie Film for Th...    0.326357  6.468935
55926                                           Next Gen    0.321058  6.988818
53093                               Mazinger Z: Infinity    0.320256  6.879147
81816                                 Fifty Percent Grey    0.320256  6.165533
85758                LEGO Star Wars: The Quest for R2-D2    0.320256  5.716185
58541                    Friends: Naki on Monster Island    0.320256  6.823049
7757                                      Robot Carnival    0.319173  6.599251
61368                     Invader Zim: Enter the Florpus    0.318142  7.327308
73169                  DreamWorks Home: For the Holidays    0.318142  5.406015
47281                                               MFKZ    0.318142  7.115925
56728                    The Satellite Girl and Milk Cow    0.318142  6.735739
15850              Evangelion: 2.0 You Can (Not) Advance    0.314945  7.772262
66865  Doraemon: Nobita and the New Steel Troops: Win...    0.311395  7.176261
80885                                  Brian and Charles    0.310726  6.315632
23161                          Scooby-Doo! Frankencreepy    0.310087  7.571445
51882             LEGO DC Comics Super Heroes: The Flash    0.310087  6.796905
47253                                              Cream    0.309016  7.006990
12477                                       Space Chimps    0.309016  4.923498
17720                    Dr. Goldfoot and the Girl Bombs    0.308145  5.136413
76610                                     Planet Unknown    0.307692  6.447937
85759                      LEGO Star Wars: Bombad Bounty    0.307692  6.137912
64083                               Ship of the Monsters    0.303822  6.158177
28626                                        Malice@Doll    0.303175  5.520596
71752                                  Jojo in the Stars    0.302952  6.218340
49335                                Batman vs. Two-Face    0.302614  6.288229
55084                            Tales from the Far Side    0.302614  6.671773
64050                        Spider-Ham: Caught in a Ham    0.302614  6.822563
85760               LEGO Star Wars: Revenge of The Brick    0.302614  5.991731
66364                                 Sex and the Future    0.299075  5.418879
64176                                      (UN)Ideal Man    0.298881  5.442190
45639                                    Genocidal Organ    0.298881  6.572974
32705                                  OMG, I'm a Robot!    0.298700  6.231727
55794  Ghost in the Shell: S.A.C. 2nd GIG - Individua...    0.297088  7.388708

Source Movie: Pigs 2: The Last Blood
                                                  title  similarity  wr_score
46351                                              Pigs    0.485947  6.968431
66974                                            Pigs 3    0.431620  6.438437
62537                                     Law of Tehran    0.366963  7.127507
56940                                             Reich    0.365843  5.269516
35122                                  With Clean Hands    0.354317  6.958822
65895                                     Panther Squad    0.353553  4.060425
35607                  Rome, the Other Face of Violence    0.351566  5.670585
67147                                             Kroll    0.351329  6.440725
26815                                             Ricco    0.351192  5.721268
51752                                         Gentleman    0.350823  6.751129
33500                           The Sicilian Connection    0.338266  5.527687
42586                                           Tik Tok    0.337570  5.706862
26693                   Death Is Nimble, Death Is Quick    0.329917  5.560551
83767                      Johan Falk: Silent Diplomacy    0.328529  6.095125
50422                                   Polish Roulette    0.327966  5.596894
36221                                        Dossier K.    0.318694  6.330743
41505                                  Fear in the City    0.318384  5.292425
34511                                     Killer Tattoo    0.317209  6.334731
23651                                     Silent Action    0.316707  5.455723
57871                           Iravukku Aayiram Kangal    0.316648  6.404975
81530                                     Surfers’ Time    0.316602  6.196032
7160                                           Raw Deal    0.313192  5.826191
80806                                            Vikram    0.312313  7.512283
23938  Johan Falk: GSI - Gruppen för särskilda insatser    0.307673  6.456889
6345                                             Tycoon    0.306786  5.353061
83764                        Johan Falk: Blood Diamonds    0.306786  6.582804
30036                                             Shool    0.301848  6.497057
23344                               A Man Called Magnum    0.300721  5.431929
31535                                     Go Gorilla Go    0.300642  6.354668
47767                             S.W.A.T.: Under Siege    0.300000  5.896823
46484                                         Racketeer    0.300000  6.616468
36100                                           Manhunt    0.300000  6.081312
31665                                 Going by the Book    0.299490  7.212213
45404                       The Story of the Kelly Gang    0.298142  5.290195
47037                        The Surrender of Tournavos    0.298142  5.137892
10446                              Executive Protection    0.293710  6.167796
37406                                           Pitbull    0.291991  6.387581
22421   A Better Tomorrow III: Love and Death in Saigon    0.290529  6.348272
80349                                    The Flying Ace    0.290518  5.896468
33110                                   Stolen Identity    0.290191  5.137021
83765                              Johan Falk: Lockdown    0.289212  6.997859
57968                                 Pitbull. Last Dog    0.288454  5.925219
23939                           Johan Falk: Vapenbröder    0.287870  6.387581
28780                                      Crimebusters    0.287242  5.370585
27167                              Women in Cellblock 9    0.286901  4.947803
41490                              Johan Falk: Leo Gaut    0.286883  6.049638
17204                                    The Dark House    0.286734  6.390103
41487                     Johan Falk: Barninfiltratören    0.286285  6.376109
49344                                          Agitator    0.286039  6.278627
37006                                           Ajnabee    0.286039  5.544479

Source Movie: Crooklyn
                                           title  similarity  wr_score
157                                     Clockers    0.417957  6.665503
3312                                Jungle Fever    0.396059  6.359578
3311                            Mo' Better Blues    0.374351  6.467357
66040                  The King of Staten Island    0.365760  6.991749
3308                         She's Gotta Have It    0.365636  6.615787
3310                          Do the Right Thing    0.360977  7.783308
8549               Love with the Proper Stranger    0.359097  6.631957
68891                                       Soul    0.353776  8.099598
2626                      Brighton Beach Memoirs    0.350477  6.419794
10261                    The Squid and the Whale    0.348302  6.936979
3309                                 School Daze    0.343171  5.702704
2592                               Summer of Sam    0.330566  6.483430
19058                            Red Hook Summer    0.326896  5.721057
3017                           Sweet and Lowdown    0.324063  6.731731
4989                                  Funny Lady    0.323616  5.372758
48346                               Little Boxes    0.322259  6.081517
21433                                Begin Again    0.321403  7.228409
27468                             Gimme the Loot    0.315177  6.138600
23006                           Listen Up Philip    0.313112  5.861514
6734                             Pieces of April    0.306844  6.468649
628                                       Girl 6    0.302868  5.078915
15156                        Come Blow Your Horn    0.300123  5.389063
35570                                    Chi-Raq    0.300123  5.744795
8192                    All I Want For Christmas    0.300123  5.654235
9357                                 She Hate Me    0.300123  5.222107
28649                              One More Time    0.299804  5.281755
28544                    Da Sweet Blood of Jesus    0.297044  5.014899
53070                           Hearts Beat Loud    0.294622  6.803669
19396                                     Bad 25    0.293057  7.043160
24140                           Cops and Robbers    0.291783  6.107900
8080                                The Sting II    0.290020  5.050127
66205                           A Dog Named Duke    0.286079  6.432270
46660  The Meyerowitz Stories (New and Selected)    0.285978  6.455595
33661            Just Another Girl on the I.R.T.    0.284850  6.428537
6993                                       Honey    0.284566  6.295827
65706                                        Abe    0.283928  6.726067
66985                 Long Nights Short Mornings    0.283148  5.289523
38690       Bela Lugosi Meets a Brooklyn Gorilla    0.281801  4.277688
28791                       Appropriate Behavior    0.281220  6.257370
6933                          That Touch of Mink    0.277218  6.364895
12986                                 Two Lovers    0.274618  6.839453
77997                                 The Humans    0.274618  6.076704
32876                                  Club Life    0.274398  5.182736
10638                                 Inside Man    0.273617  7.392944
29053                                Dirty Hands    0.271163  6.307900
28492                            Without a Trace    0.270546  5.512434
1025                              Get on the Bus    0.269676  6.243785
2051                      Slums of Beverly Hills    0.269311  6.259636
35512                               Downtown '81    0.269069  6.408530
42780                                    Honey 2    0.269069  6.287878

Source Movie: The Condemned of Altona
                                   title  similarity  wr_score
33771               Girl with a Suitcase    0.435664  7.038592
10314                        The Swindle    0.385758  7.271196
30185                      The Swindlers    0.385758  6.149504
65587          When You Read This Letter    0.350506  5.915999
30188  Policarpo, ufficiale di scrittura    0.334011  6.912788
29752           Venice, the Moon and You    0.333943  5.882196
37902                     Violent Summer    0.331482  7.111874
7618                  Sodom and Gomorrah    0.331133  5.486758
33589                 Poor But Beautiful    0.320256  6.662277
17542                     The Vanquished    0.320256  6.307352
33588                Scandal in Sorrento    0.306186  6.872931
30198                  The Sign of Venus    0.306186  6.758261
29751                    Fiasco in Milan    0.288675  6.826428
74025                 Duel of the Titans    0.288675  5.497005
28848                           Paranoia    0.280056  5.924779
36069                           The Roof    0.263190  7.195489
7982                         The Leopard    0.261666  7.686853
48206        The Miller's Beautiful Wife    0.261116  5.566240
3689                           Two Women    0.255730  7.777264
17161                 The Gold of Naples    0.250582  7.237841
15985                    The Rothschilds    0.241258  6.087929
68029                        Finis Terræ    0.240192  6.857813
5548                       The Grey Zone    0.231125  6.578888
14045             Marriage Italian Style    0.223607  7.677800
10040               General Della Rovere    0.222222  7.350953
27707              His Days are Numbered    0.218218  6.994868
64834                Bandits of Orgosolo    0.218218  7.303065
8541             The Four Days of Naples    0.216506  7.326510
6458          The Man in the Glass Booth    0.213507  6.162686
24024              Dangerously They Live    0.207689  6.117909
15571                      Days of Glory    0.204869  5.932927
25156                    The Rose Garden    0.204639  6.372275
22173               She Devils of the SS    0.204579  5.121615
40524         Next Year If All Goes Well    0.204124  5.874129
34884                             Frisky    0.204124  7.086808
15748             The Silence of the Sea    0.201704  7.443638